apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: tssc-dev 
  janus-idp.io/tekton: tssc-dev
  backstage.io/kubernetes-id: tssc-dev
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tssc-dev
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  