apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tssc-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jduimovich0/bootstrap:jenkins-ce9648d8494af6159af6c0ed923e78472417bd61
          name: container-image
