apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tssc-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jduimovich0/private-image:jenkins-4d399dc8e2642aa7779809bdb0caa5b870d6b44b
          name: container-image
