apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tssc-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jduimovich0/private-image:jenkins-0b3cc84615f8fe58a61eebcfcd2600085ce99991
          name: container-image
