apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: tssc-dev
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jduimovich0/private-image:jenkins-2228e708f7475912740f87779bf951c98c8ec555
          name: container-image
